env:
  browser: true
  commonjs: true
  es6: true
  node: true
  jest: true
extends: ['eslint:recommended', 'airbnb-base']
parserOptions:
  ecmaVersion: 2017
  sourceType: module
rules:
  indent:
    - error
    - 4
  linebreak-style:
    - error
    - unix
  quotes:
    - error
    - single
  semi:
    - error
    - always
  max-len:
    - error
    - code: 150
  no-console: off
  object-curly-spacing:
    - error
    - always
